# This config file renders the "primer-spec" theme from:
# https://github.com/eecs485staff/primer-spec
# This theme is built on the default GitHub Markdown theme "Primer", and
# optionally renders a sidebar to easily navigate the document.

title: "react-workshop"
repository: void-tech-um/react-workshop

# Jekyll build settings
remote_theme: eecs485staff/primer-spec
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-github-metadata
kramdown:
  input: GFM
readme_index:
  remove_originals: true
  with_frontmatter: true

primerSpec:
  sitemap:
    label: Tutorials
